Oop task1
AleksandrMatsko/OOP-Java pull request #2
Opened 2022-02-18 13:24 UTC by AleksandrMatsko

2022-02-19 05:35 UTC, DNGor requested changes

2022-02-19 05:35 UTC, DNGor commented on task1_parser/WordCounter.java
> +        dataReader.close();
Закрытие ресурса стало не надёжным

2022-02-19 05:35 UTC, DNGor commented on task1_parser/WordCounter.java
> +        dataWriter.close();
Закрытие ресурса стало не надёжным

2022-02-19 12:18 UTC, AleksandrMatsko commented
Исправление должно выглядеть как-то так?

2022-02-21 05:59 UTC, DNGor requested changes

2022-02-21 05:59 UTC, DNGor commented on task1_parser/Main.java
> +        if (outputStream != null) {
Выше сделано правильно, тут - нет. Изучите пожалуйста, как работает секция finally.

2022-02-21 10:23 UTC, merged